In [1]:
from pyspark.sql import SparkSession

spark = (
    SparkSession.builder
    .appName("Spotify Metadata Analysis") #this is the line im unsure of
    .config("spark.driver.memory", "2g")
    .config("spark.executor.memory", "18g")
    .config('spark.executor.instances', 7)
    .getOrCreate()
)
#double check

In [2]:
#spotify_clean_parquet
#df = spark.read.parquet("/expanse/lustre/projects/uci157/zlenus/shared/spotify_clean_parquet")
tracks = spark.read.parquet("/expanse/lustre/projects/uci157/zlenus/shared/spotify_clean_parquet/tracks.parquet")
available_markets= spark.read.parquet("/expanse/lustre/projects/uci157/zlenus/shared/spotify_clean_parquet/available_markets.parquet")
track_artists = spark.read.parquet("/expanse/lustre/projects/uci157/zlenus/shared/spotify_clean_parquet/track_artists.parquet")
artists = spark.read.parquet("/expanse/lustre/projects/uci157/zlenus/shared/spotify_clean_parquet/artists.parquet")
artist_genres = spark.read.parquet("/expanse/lustre/projects/uci157/zlenus/shared/spotify_clean_parquet/artist_genres.parquet")
artist_albums = spark.read.parquet("/expanse/lustre/projects/uci157/zlenus/shared/spotify_clean_parquet/artist_albums.parquet")
albums = spark.read.parquet("/expanse/lustre/projects/uci157/zlenus/shared/spotify_clean_parquet/albums.parquet")

In [3]:
tracks.count() + available_markets.count() + track_artists.count() + artists.count() + artist_genres.count() + artist_albums.count() + albums.count()

792244463

In [4]:
tracks.printSchema()

root
 |-- rowid: long (nullable = true)
 |-- id: string (nullable = true)
 |-- fetched_at: long (nullable = true)
 |-- name: string (nullable = true)
 |-- preview_url: string (nullable = true)
 |-- album_rowid: long (nullable = true)
 |-- track_number: long (nullable = true)
 |-- external_id_isrc: string (nullable = true)
 |-- popularity: long (nullable = true)
 |-- available_markets_rowid: long (nullable = true)
 |-- disc_number: long (nullable = true)
 |-- duration_ms: long (nullable = true)
 |-- explicit: long (nullable = true)

In [5]:
available_markets.printSchema()

root
 |-- rowid: long (nullable = true)
 |-- available_markets: string (nullable = true)

In [6]:
track_artists.printSchema()

root
 |-- track_rowid: long (nullable = true)
 |-- artist_rowid: long (nullable = true)

In [7]:
artists.printSchema()

root
 |-- rowid: long (nullable = true)
 |-- id: string (nullable = true)
 |-- fetched_at: long (nullable = true)
 |-- name: string (nullable = true)
 |-- followers_total: long (nullable = true)
 |-- popularity: long (nullable = true)

In [8]:
artist_genres.printSchema()

root
 |-- artist_rowid: long (nullable = true)
 |-- genre: string (nullable = true)

In [9]:
artist_albums.printSchema()

root
 |-- artist_rowid: long (nullable = true)
 |-- album_rowid: long (nullable = true)
 |-- is_appears_on: long (nullable = true)
 |-- is_implicit_appears_on: long (nullable = true)
 |-- index_in_album: long (nullable = true)

In [10]:
albums.printSchema()

root
 |-- rowid: long (nullable = true)
 |-- id: string (nullable = true)
 |-- fetched_at: long (nullable = true)
 |-- name: string (nullable = true)
 |-- album_type: string (nullable = true)
 |-- available_markets_rowid: long (nullable = true)
 |-- external_id_upc: string (nullable = true)
 |-- copyright_c: string (nullable = true)
 |-- copyright_p: string (nullable = true)
 |-- label: string (nullable = true)
 |-- popularity: long (nullable = true)
 |-- release_date: string (nullable = true)
 |-- release_date_precision: string (nullable = true)
 |-- total_tracks: long (nullable = true)
 |-- external_id_amgid: string (nullable = true)

In [11]:
from pyspark.sql.functions import col, count, when

null_counts = tracks.select([
    count(when(col(c).isNull(), c)).alias(c)
    for c in tracks.columns
])

null_counts.show()
null_counts_pd = null_counts.toPandas()
null_counts_pd

+-----+---+----------+----+-----------+-----------+------------+----------------+----------+-----------------------+-----------+-----------+--------+
|rowid| id|fetched_at|name|preview_url|album_rowid|track_number|external_id_isrc|popularity|available_markets_rowid|disc_number|duration_ms|explicit|
+-----+---+----------+----+-----------+-----------+------------+----------------+----------+-----------------------+-----------+-----------+--------+
|    0|  0|         0|   0|   25410128|          0|           0|          104792|         0|                      0|          0|          0|       0|
+-----+---+----------+----+-----------+-----------+------------+----------------+----------+-----------------------+-----------+-----------+--------+

,rowid,id,fetched_at,name,preview_url,album_rowid,track_number,external_id_isrc,popularity,available_markets_rowid,disc_number,duration_ms,explicit
0,0,0,0,0,25410128,0,0,104792,0,0,0,0,0

In [12]:
null_counts = available_markets.select([
    count(when(col(c).isNull(), c)).alias(c)
    for c in available_markets.columns
])

null_counts.show()
null_counts_pd = null_counts.toPandas()
null_counts_pd

+-----+-----------------+
|rowid|available_markets|
+-----+-----------------+
|    0|                0|
+-----+-----------------+

   rowid  available_markets
0      0                  0

In [13]:
null_counts = track_artists.select([
    count(when(col(c).isNull(), c)).alias(c)
    for c in track_artists.columns
])

null_counts.show()
null_counts_pd = null_counts.toPandas()
null_counts_pd

+-----------+------------+
|track_rowid|artist_rowid|
+-----------+------------+
|          0|           0|
+-----------+------------+

   track_rowid  artist_rowid
0            0             0

In [14]:
null_counts = artists.select([
    count(when(col(c).isNull(), c)).alias(c)
    for c in artists.columns
])

null_counts.show()
null_counts_pd = null_counts.toPandas()
null_counts_pd

+-----+---+----------+----+---------------+----------+
|rowid| id|fetched_at|name|followers_total|popularity|
+-----+---+----------+----+---------------+----------+
|    0|  0|         0|   0|              0|         0|
+-----+---+----------+----+---------------+----------+

   rowid  id  fetched_at  name  followers_total  popularity
0      0   0           0     0                0           0

In [15]:
null_counts = artist_genres.select([
    count(when(col(c).isNull(), c)).alias(c)
    for c in artist_genres.columns
])

null_counts.show()
null_counts_pd = null_counts.toPandas()
null_counts_pd

+------------+-----+
|artist_rowid|genre|
+------------+-----+
|           0|    0|
+------------+-----+

   artist_rowid  genre
0             0      0

In [16]:
null_counts = artist_albums.select([
    count(when(col(c).isNull(), c)).alias(c)
    for c in artist_albums.columns
])

null_counts.show()
null_counts_pd = null_counts.toPandas()
null_counts_pd

+------------+-----------+-------------+----------------------+--------------+
|artist_rowid|album_rowid|is_appears_on|is_implicit_appears_on|index_in_album|
+------------+-----------+-------------+----------------------+--------------+
|           0|          0|            0|                     0|      45093900|
+------------+-----------+-------------+----------------------+--------------+

,artist_rowid,album_rowid,is_appears_on,is_implicit_appears_on,index_in_album
0,0,0,0,0,45093900

In [17]:
null_counts = albums.select([
    count(when(col(c).isNull(), c)).alias(c)
    for c in albums.columns
])

null_counts.show()
null_counts_pd = null_counts.toPandas()
null_counts_pd

+-----+---+----------+----+----------+-----------------------+---------------+-----------+-----------+-----+----------+------------+----------------------+------------+-----------------+
|rowid| id|fetched_at|name|album_type|available_markets_rowid|external_id_upc|copyright_c|copyright_p|label|popularity|release_date|release_date_precision|total_tracks|external_id_amgid|
+-----+---+----------+----+----------+-----------------------+---------------+-----------+-----------+-----+----------+------------+----------------------+------------+-----------------+
|    0|  0|         0|   0|         0|                      0|          48056|     907818|    1195597|    0|         0|           0|                     0|           0|         58574587|
+-----+---+----------+----+----------+-----------------------+---------------+-----------+-----------+-----+----------+------------+----------------------+------------+-----------------+

,rowid,id,fetched_at,name,album_type,available_markets_rowid,external_id_upc,copyright_c,copyright_p,label,popularity,release_date,release_date_precision,total_tracks,external_id_amgid
0,0,0,0,0,0,0,48056,907818,1195597,0,0,0,0,0,58574587

In [31]:
available_markets.limit(5).toPandas()

   rowid                                  available_markets
0      1                                        unavailable
1      2  AR,AU,AT,BE,BO,BR,BG,CA,CL,CO,CR,CY,CZ,DK,DO,D...
2      3  AR,AU,AT,BE,BO,BR,BG,CA,CL,CO,CR,CY,CZ,DK,DO,D...
3      4  AR,AU,AT,BE,BO,BR,BG,CA,CL,CO,CR,CY,CZ,DK,DO,D...
4      5  AR,AU,AT,BE,BO,BR,BG,CL,CO,CR,CY,CZ,DK,DO,DE,E...

In [34]:
from pyspark.sql.functions import count

top_artists = (
    tracks.groupBy("artist_name")
    .agg(count("*").alias("num_tracks"))
    .orderBy("num_tracks", ascending=False)
    .limit(10)
)

AnalysisException: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `artist_name` cannot be resolved. Did you mean one of the following? [`disc_number`, `name`, `duration_ms`, `fetched_at`, `id`].;
'Aggregate ['artist_name], ['artist_name, count(1) AS num_tracks#881L]
+- Relation [rowid#0L,id#1,fetched_at#2L,name#3,preview_url#4,album_rowid#5L,track_number#6L,external_id_isrc#7,popularity#8L,available_markets_rowid#9L,disc_number#10L,duration_ms#11L,explicit#12L] parquet

In [35]:
top_artists_pd = top_artists.toPandas()

NameError: name 'top_artists' is not defined

In [36]:
import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))
plt.bar(top_artists_pd["artist_name"], top_artists_pd["num_tracks"])
plt.xticks(rotation=45, ha="right")
plt.title("Top 10 Artists by Number of Tracks")
plt.xlabel("Artist")
plt.ylabel("Track Count")
plt.show()

NameError: name 'top_artists_pd' is not defined